show databases
create database mysql_test;
use mysql_test;
show tables;
create table test1(
ID int,
TextData varchar(255);
alter table test1 change TextData TextData longtext;
select * from test1;
insert into test1 values (1, "30.14 NZD (28.542%) NZ001, Not Required-Use Accounting Treatment-83275:Wellington-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83275:Wellington (83275:Wellington), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 75.46 NZD (71.458%) NZ001, Not Required-Use Accounting Treatment-84472:Wellington Actuarial Consult-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 84472:Wellington Actuarial Consult (84472:Wellington Actuarial Consult), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE)");
insert into test1 values (2, "30.14 NZD (28.542%) NZ001, Not Required-Use Accounting Treatment-83275:Wellington-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83275:Wellington (83275:Wellington), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 75.46 NZD (71.458%) NZ001, Not Required-Use Accounting Treatment-84472:Wellington Actuarial Consult-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 84472:Wellington Actuarial Consult (84472:Wellington Actuarial Consult), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE)");
insert into test1 values (3, "23.82 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 11.91 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE)");
insert into test1 values (4, "23.82 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 11.91 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE)");
insert into test1 values (5, "39.68 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 19.84 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE)");
insert into test1 values (6, "39.68 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 19.84 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE)");
insert into test1 values (7, "2461.42 AUD (59.849%) AU021, Not Required-Use Accounting Treatment-82905:Operations   National-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82905:Operations   National (82905:Operations   National), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 1,096.42 AUD (26.659%) AU021, Not Required-Use Accounting Treatment-82908:AU VIC Melbourne 80 Collins St-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82908:AU VIC Melbourne 80 Collins St (82908:AU VIC Melbourne 80 Collins St), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82911:AU WA Perth 28 The Esplande-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82911:AU WA Perth 28 The Esplande (82911:AU WA Perth 28 The Esplande), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82912:AU SA Adelaide 91 King William-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82912:AU SA Adelaide 91 King William (82912:AU SA Adelaide 91 King William), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES)");
insert into test1 values (8, "2461.42 AUD (59.849%) AU021, Not Required-Use Accounting Treatment-82905:Operations   National-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82905:Operations   National (82905:Operations   National), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 1,096.42 AUD (26.659%) AU021, Not Required-Use Accounting Treatment-82908:AU VIC Melbourne 80 Collins St-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82908:AU VIC Melbourne 80 Collins St (82908:AU VIC Melbourne 80 Collins St), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82911:AU WA Perth 28 The Esplande-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82911:AU WA Perth 28 The Esplande (82911:AU WA Perth 28 The Esplande), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82912:AU SA Adelaide 91 King William-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82912:AU SA Adelaide 91 King William (82912:AU SA Adelaide 91 King William), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES)");
select * from test1;

/* Q1. Write a query to get whatever is between 4th and 5th Comma (,) From TextData column */

SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(TextData, ',' , 5), ',', -1) AS Result_1 FROM test1;

/* Q2. Write a query to get whatever is between 1st and 2nd colon (:) between 4th and 5th Comma (,) From TextData column */

SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(TextData, ',' , 5), ',', -1), ':',2),':',-1) AS Result_2 FROM test1;